#!/bin/sh

ENABLED=yes
PROCS=ps3netsrv_arm
ARGS="/tmp/mnt/sda2/PS3SMB"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func