slides = [
{img:'XMBMANPLS/USRDIR/IMAGES/settings.png',width:300,height:300,desc:'CUSTOM COMBO - <font color="cyan">R2 + SQUARE',url:'/edit.ps3/dev_hdd0/tmp/wm_combo/wm_custom_r2_square'},
{img:'XMBMANPLS/USRDIR/IMAGES/settings.png',width:300,height:300,desc:'REFRESH XML - <font color="yellow">SELECT + L3',url:'/edit.ps3/dev_hdd0/tmp/wm_combo/wm_custom_select_l3'},
{img:'XMBMANPLS/USRDIR/IMAGES/settings.png',width:300,height:300,desc:'GO TO HOME - <font color="yellow">L3 + R3 + L2',url:'/edit.ps3/dev_hdd0/tmp/wm_combo/wm_custom_l3_r3_l2'},
{img:'XMBMANPLS/USRDIR/IMAGES/settings.png',width:300,height:300,desc:'PLAY DISC - <font color="yellow">L2 + START',url:'/edit.ps3/dev_hdd0/tmp/wm_combo/wm_custom_l2_start'},
{img:'XMBMANPLS/USRDIR/IMAGES/settings.png',width:300,height:300,desc:'PLAY APP_HOME - <font color="yellow">R2 + START',url:'/edit.ps3/dev_hdd0/tmp/wm_combo/wm_custom_r2_start'},
{img:'XMBMANPLS/USRDIR/IMAGES/settings.png',width:300,height:300,desc:'PREV GAME - <font color="yellow">SELECT + L1',url:'/edit.ps3/dev_hdd0/tmp/wm_combo/wm_custom_select_l1'},
{img:'XMBMANPLS/USRDIR/IMAGES/settings.png',width:300,height:300,desc:'NEXT GAME - <font color="yellow">SELECT + R1',url:'/edit.ps3/dev_hdd0/tmp/wm_combo/wm_custom_select_r1'},
{img:'XMBMANPLS/USRDIR/IMAGES/settings.png',width:300,height:300,desc:'UNMOUNT GAME - <font color="yellow">SELECT + CIRCLE',url:'/edit.ps3/dev_hdd0/tmp/wm_combo/wm_custom_select_circle'},
{img:'XMBMANPLS/USRDIR/IMAGES/settings.png',width:300,height:300,desc:'RESERVED1 - <font color="yellow">SELECT + TRIANGLE',url:'/edit.ps3/dev_hdd0/tmp/wm_combo/wm_custom_select_triangle'},
{img:'XMBMANPLS/USRDIR/IMAGES/settings.png',width:300,height:300,desc:'RESERVED2 - <font color="yellow">SELECT + CROSS',url:'/edit.ps3/dev_hdd0/tmp/wm_combo/wm_custom_select_cross'},
{img:'XMBMANPLS/USRDIR/IMAGES/settings.png',width:300,height:300,desc:'EXTERNAL GAME DATA - <font color="yellow">SELECT + SQUARE',url:'/edit.ps3/dev_hdd0/tmp/wm_combo/wm_custom_select_square'},
{img:'XMBMANPLS/USRDIR/IMAGES/settings.png',width:300,height:300,desc:'DYNAMIC TEMP LESS - <font color="yellow">SELECT + LEFT',url:'/edit.ps3/dev_hdd0/tmp/wm_combo/wm_custom_select_left'},
{img:'XMBMANPLS/USRDIR/IMAGES/settings.png',width:300,height:300,desc:'DYNAMIC TEMP MORE - <font color="yellow">SELECT + RIGHT',url:'/edit.ps3/dev_hdd0/tmp/wm_combo/wm_custom_select_right'},
{img:'XMBMANPLS/USRDIR/IMAGES/settings.png',width:300,height:300,desc:'MANUAL TEMP LESS - <font color="yellow">SELECT + DOWN',url:'/edit.ps3/dev_hdd0/tmp/wm_combo/wm_custom_select_down'},
{img:'XMBMANPLS/USRDIR/IMAGES/settings.png',width:300,height:300,desc:'MANUAL TEMP MORE - <font color="yellow">SELECT + UP',url:'/edit.ps3/dev_hdd0/tmp/wm_combo/wm_custom_select_up'},
{img:'XMBMANPLS/USRDIR/IMAGES/settings.png',width:300,height:300,desc:'RECORD IN-GAME VIDEO - <font color="yellow">SELECT + R3',url:'/edit.ps3/dev_hdd0/tmp/wm_combo/wm_custom_select_r3'},
{img:'XMBMANPLS/USRDIR/IMAGES/settings.png',width:300,height:300,desc:'XMB SCREENSHOT - <font color="yellow">L2 + R2 + SELECT + START',url:'/edit.ps3/dev_hdd0/tmp/wm_combo/wm_custom_l2_r2_select_start'},
{img:'XMBMANPLS/USRDIR/IMAGES/settings.png',width:300,height:300,desc:'USER/ADMIN MODE - <font color="yellow">L2 + R2 + TRIANGLE',url:'/edit.ps3/dev_hdd0/tmp/wm_combo/wm_custom_l2_r2_triangle'},
{img:'XMBMANPLS/USRDIR/IMAGES/settings.png',width:300,height:300,desc:'DISABLE CFW SYSCALLS - <font color="yellow">R2 + TRIANGLE',url:'/edit.ps3/dev_hdd0/tmp/wm_combo/wm_custom_r2_triangle'},
{img:'XMBMANPLS/USRDIR/IMAGES/settings.png',width:300,height:300,desc:'SHOW IDPS - <font color="yellow">R2 + CIRCLE',url:'/edit.ps3/dev_hdd0/tmp/wm_combo/wm_custom_r2_circle'},
{img:'XMBMANPLS/USRDIR/IMAGES/settings.png',width:300,height:300,desc:'QUICK INSTALL - <font color="yellow">SELECT + R2 + CIRCLE',url:'/edit.ps3/dev_hdd0/tmp/wm_combo/wm_custom_select_r2_circle'},
{img:'XMBMANPLS/USRDIR/IMAGES/settings.png',width:300,height:300,desc:'OPEN FILE MANAGER - <font color="yellow">L2 + R2 + CIRCLE',url:'/edit.ps3/dev_hdd0/tmp/wm_combo/wm_custom_l2_r2_circle'},
{img:'XMBMANPLS/USRDIR/IMAGES/settings.png',width:300,height:300,desc:'OPEN GAMES LIST - <font color="yellow">L2 + R2 + R1 + CIRCLE',url:'/edit.ps3/dev_hdd0/tmp/wm_combo/wm_custom_l2_r2_r1_circle'},
{img:'XMBMANPLS/USRDIR/IMAGES/settings.png',width:300,height:300,desc:'OPEN SYSTEM INFO - <font color="yellow">L2 + R2 + L1 + CIRCLE',url:'/edit.ps3/dev_hdd0/tmp/wm_combo/wm_custom_l2_r2_l1_circle'},
{img:'XMBMANPLS/USRDIR/IMAGES/settings.png',width:300,height:300,desc:'OPEN SETUP - <font color="yellow">L2 + R2 + L1 + R1 + CIRCLE',url:'/edit.ps3/dev_hdd0/tmp/wm_combo/wm_custom_l2_r2_l1_r1_circle'},
];

