name: build-webman-mod (PSL1GHT)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    container:
      image: ghcr.io/ps3dev/ps3dev:latest   # ← use GHCR instead of Docker Hub

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show toolchain versions
        run: |
          which ppu-gcc || true
          ppu-gcc --version || true
          make --version

      - name: Build SPRX + PKG
        run: |
          make clean
          make -j"$(nproc)"
          make pkg || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webMAN_MOD_artifacts
          if-no-files-found: warn
          path: |
            **/webftp_server.sprx
            **/*.pkg
