name: build-webman-mod (PSL1GHT)

on:
  workflow_dispatch:        # “Run workflow” button
  push:
    branches: [ main ]      # auto-build on pushes to main
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    # Use prebuilt PS3 toolchain so we don't compile the SDK every run
    container: ps3dev/ps3dev:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Show toolchain versions
        run: |
          which ppu-gcc || true
          ppu-gcc --version || true
          make --version

      - name: Build SPRX + PKG
        run: |
          make clean
          make -j"$(nproc)"
          make pkg || true   # if pkg target exists, produce a .pkg

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webMAN_MOD_artifacts
          if-no-files-found: warn
          path: |
            PKGFILES/USRDIR/webftp_server.sprx
            pkg/*.pkg

